/*
   Kafel - syscalls (TEMPLATE_ARCH)
   -----------------------------------------

   Copyright 2016 Google Inc. All Rights Reserved.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

*/

#include "../syscall.h"

#include <stddef.h>

#define ARG_0 0
#define ARG_1 1
#define ARG_2 2
#define ARG_3 3
#define ARG_4 4
#define ARG_5 5

#define NORMAL false

const struct syscall_descriptor TEMPLATE_ARCH_syscall_list[] = {
    {"accept",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"upeer_sockaddr", 4},
             [ARG_2] = {"upeer_addrlen", 4},
     }},
    {"accept4",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"upeer_sockaddr", 4},
             [ARG_2] = {"upeer_addrlen", 4}, [ARG_3] = {"flags", 4},
     }},
    {"access",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 4}, [ARG_1] = {"mode", 4},
     }},
    {"acct",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"name", 4},
     }},
    {"add_key",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"_type", 4}, [ARG_1] = {"_description", 4},
             [ARG_2] = {"_payload", 4}, [ARG_3] = {"plen", 4},
             [ARG_4] = {"ringid", 4},
     }},
    {"adjtimex",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"txc_p", 4},
     }},
    {"alarm",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"seconds", 4},
     }},  // obsolete, no longer available for EABI
    {"arm_fadvise64_64",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"offset", 8}, [ARG_2] = {"len", 8},
     }},
    {"bdflush",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"func", 4}, [ARG_1] = {"data", 4},
     }},
    {"bind",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"umyaddr", 4},
             [ARG_2] = {"addrlen", 4},
     }},
    {"bpf",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"cmd", 4}, [ARG_1] = {"uattr", 4},
             [ARG_2] = {"size", 4},
     }},
    {"breakpoint", 983041, NORMAL, {}},
    {"brk",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"brk", 4},
     }},
    {"cacheflush",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"vaddr_from", 4}, [ARG_1] = {"vaddr_to", 4},
             [ARG_2] = {"flags", 4},
     }},
    {"capget",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"header", 4}, [ARG_1] = {"dataptr", 4},
     }},
    {"capset",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"header", 4}, [ARG_1] = {"data", 4},
     }},
    {"chdir",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 4},
     }},
    {"chmod",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 4}, [ARG_1] = {"mode", 2},
     }},
    {"chown",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 4}, [ARG_1] = {"user", 4},
             [ARG_2] = {"group", 4},
     }},
    {"chown16",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 4}, [ARG_1] = {"user", 2},
             [ARG_2] = {"group", 2},
     }},
    {"chroot",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 4},
     }},
    {"clock_adjtime",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which_clock", 4}, [ARG_1] = {"utx", 4},
     }},
    {"clock_getres",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which_clock", 4}, [ARG_1] = {"tp", 4},
     }},
    {"clock_gettime",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which_clock", 4}, [ARG_1] = {"tp", 4},
     }},
    {"clock_nanosleep",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which_clock", 4}, [ARG_1] = {"flags", 4},
             [ARG_2] = {"rqtp", 4}, [ARG_3] = {"rmtp", 4},
     }},
    {"clock_settime",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which_clock", 4}, [ARG_1] = {"tp", 4},
     }},
    {"clone",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"clone_flags", 4}, [ARG_1] = {"newsp", 4},
             [ARG_2] = {"parent_tidptr", 4}, [ARG_3] = {"tls", 4},
             [ARG_4] = {"child_tidptr", 4},
     }},
    {"close",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4},
     }},
    {"connect",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"uservaddr", 4},
             [ARG_2] = {"addrlen", 4},
     }},
    {"copy_file_range",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd_in", 4}, [ARG_1] = {"off_in", 4},
             [ARG_2] = {"fd_out", 4}, [ARG_3] = {"off_out", 4},
             [ARG_4] = {"len", 4}, [ARG_5] = {"flags", 4},
     }},
    {"creat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 4}, [ARG_1] = {"mode", 2},
     }},
    {"delete_module",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"name_user", 4}, [ARG_1] = {"flags", 4},
     }},
    {"dup",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fildes", 4},
     }},
    {"dup2",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"oldfd", 4}, [ARG_1] = {"newfd", 4},
     }},
    {"dup3",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"oldfd", 4}, [ARG_1] = {"newfd", 4},
             [ARG_2] = {"flags", 4},
     }},
    {"epoll_create",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"size", 4},
     }},
    {"epoll_create1",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"flags", 4},
     }},
    {"epoll_ctl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"epfd", 4}, [ARG_1] = {"op", 4}, [ARG_2] = {"fd", 4},
             [ARG_3] = {"event", 4},
     }},
    {"epoll_pwait",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"epfd", 4}, [ARG_1] = {"events", 4},
             [ARG_2] = {"maxevents", 4}, [ARG_3] = {"timeout", 4},
             [ARG_4] = {"sigmask", 4}, [ARG_5] = {"sigsetsize", 4},
     }},
    {"epoll_wait",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"epfd", 4}, [ARG_1] = {"events", 4},
             [ARG_2] = {"maxevents", 4}, [ARG_3] = {"timeout", 4},
     }},
    {"eventfd",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"count", 4},
     }},
    {"eventfd2",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"count", 4}, [ARG_1] = {"flags", 4},
     }},
    {"execve",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 4}, [ARG_1] = {"argv", 4},
             [ARG_2] = {"envp", 4},
     }},
    {"execveat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"filename", 4},
             [ARG_2] = {"argv", 4}, [ARG_3] = {"envp", 4},
             [ARG_4] = {"flags", 4},
     }},
    {"exit",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"error_code", 4},
     }},
    {"exit_group",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"error_code", 4},
     }},
    {"faccessat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"filename", 4},
             [ARG_2] = {"mode", 4},
     }},
    {"fallocate",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"mode", 4},
             [ARG_2] = {"offset", 8}, [ARG_3] = {"len", 8},
     }},
    {"fanotify_init",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"flags", 4}, [ARG_1] = {"event_f_flags", 4},
     }},
    {"fanotify_mark",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fanotify_fd", 4}, [ARG_1] = {"flags", 4},
             [ARG_2] = {"mask", 8}, [ARG_3] = {"dfd", 4},
             [ARG_4] = {"pathname", 4},
     }},
    {"fchdir",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4},
     }},
    {"fchmod",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"mode", 2},
     }},
    {"fchmodat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"filename", 4},
             [ARG_2] = {"mode", 2},
     }},
    {"fchown",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"user", 4}, [ARG_2] = {"group", 4},
     }},
    {"fchown16",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"user", 2}, [ARG_2] = {"group", 2},
     }},
    {"fchownat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"filename", 4},
             [ARG_2] = {"user", 4}, [ARG_3] = {"group", 4},
             [ARG_4] = {"flag", 4},
     }},
    {"fcntl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"cmd", 4}, [ARG_2] = {"arg", 4},
     }},
    {"fcntl64",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"cmd", 4}, [ARG_2] = {"arg", 4},
     }},
    {"fdatasync",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4},
     }},
    {"fgetxattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"name", 4}, [ARG_2] = {"value", 4},
             [ARG_3] = {"size", 4},
     }},
    {"finit_module",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"uargs", 4},
             [ARG_2] = {"flags", 4},
     }},
    {"flistxattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"list", 4}, [ARG_2] = {"size", 4},
     }},
    {"flock",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"cmd", 4},
     }},
    {"fork", 2, NORMAL, {}},
    {"fremovexattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"name", 4},
     }},
    {"fsetxattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"name", 4}, [ARG_2] = {"value", 4},
             [ARG_3] = {"size", 4}, [ARG_4] = {"flags", 4},
     }},
    {"fstat64",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"statbuf", 4},
     }},
    {"fstatat64",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"filename", 4},
             [ARG_2] = {"statbuf", 4}, [ARG_3] = {"flag", 4},
     }},
    {"fstatfs",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"buf", 4},
     }},
    {"fstatfs64",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"sz", 4}, [ARG_2] = {"buf", 4},
     }},
    {"fsync",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4},
     }},
    {"ftruncate",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"length", 4},
     }},
    {"ftruncate64",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"length", 8},
     }},
    {"futex",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"uaddr", 4}, [ARG_1] = {"op", 4}, [ARG_2] = {"val", 4},
             [ARG_3] = {"utime", 4}, [ARG_4] = {"uaddr2", 4},
             [ARG_5] = {"val3", 4},
     }},
    {"futimesat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"filename", 4},
             [ARG_2] = {"utimes", 4},
     }},
    {"getcpu",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"cpup", 4}, [ARG_1] = {"nodep", 4},
             [ARG_2] = {"unused", 4},
     }},
    {"getcwd",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"buf", 4}, [ARG_1] = {"size", 4},
     }},
    {"getdents",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"dirent", 4},
             [ARG_2] = {"count", 4},
     }},
    {"getdents64",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"dirent", 4},
             [ARG_2] = {"count", 4},
     }},
    {"getegid", 202, NORMAL, {}},
    {"getegid16", 50, NORMAL, {}},
    {"geteuid", 201, NORMAL, {}},
    {"geteuid16", 49, NORMAL, {}},
    {"getgid", 200, NORMAL, {}},
    {"getgid16", 47, NORMAL, {}},
    {"getgroups",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"gidsetsize", 4}, [ARG_1] = {"grouplist", 4},
     }},
    {"getgroups16",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"gidsetsize", 4}, [ARG_1] = {"grouplist", 4},
     }},
    {"getitimer",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which", 4}, [ARG_1] = {"value", 4},
     }},
    {"get_mempolicy",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"policy", 4}, [ARG_1] = {"nmask", 4},
             [ARG_2] = {"maxnode", 4}, [ARG_3] = {"addr", 4},
             [ARG_4] = {"flags", 4},
     }},
    {"getpeername",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"usockaddr", 4},
             [ARG_2] = {"usockaddr_len", 4},
     }},
    {"getpgid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4},
     }},
    {"getpgrp", 65, NORMAL, {}},
    {"getpid", 20, NORMAL, {}},
    {"getppid", 64, NORMAL, {}},
    {"getpriority",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which", 4}, [ARG_1] = {"who", 4},
     }},
    {"getrandom",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"buf", 4}, [ARG_1] = {"count", 4},
             [ARG_2] = {"flags", 4},
     }},
    {"getresgid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"rgidp", 4}, [ARG_1] = {"egidp", 4},
             [ARG_2] = {"sgidp", 4},
     }},
    {"getresgid16",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"rgidp", 4}, [ARG_1] = {"egidp", 4},
             [ARG_2] = {"sgidp", 4},
     }},
    {"getresuid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ruidp", 4}, [ARG_1] = {"euidp", 4},
             [ARG_2] = {"suidp", 4},
     }},
    {"getresuid16",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ruidp", 4}, [ARG_1] = {"euidp", 4},
             [ARG_2] = {"suidp", 4},
     }},
    {"getrlimit",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"resource", 4}, [ARG_1] = {"rlim", 4},
     }},
    {"get_robust_list",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"head_ptr", 4},
             [ARG_2] = {"len_ptr", 4},
     }},
    {"getrusage",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"who", 4}, [ARG_1] = {"ru", 4},
     }},
    {"getsid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4},
     }},
    {"getsockname",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"usockaddr", 4},
             [ARG_2] = {"usockaddr_len", 4},
     }},
    {"getsockopt",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"level", 4},
             [ARG_2] = {"optname", 4}, [ARG_3] = {"optval", 4},
             [ARG_4] = {"optlen", 4},
     }},
    {"gettid", 224, NORMAL, {}},
    {"gettimeofday",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"tv", 4}, [ARG_1] = {"tz", 4},
     }},
    {"getuid", 199, NORMAL, {}},
    {"getuid16", 24, NORMAL, {}},
    {"getxattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 4}, [ARG_1] = {"name", 4},
             [ARG_2] = {"value", 4}, [ARG_3] = {"size", 4},
     }},
    {"init_module",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"umod", 4}, [ARG_1] = {"len", 4},
             [ARG_2] = {"uargs", 4},
     }},
    {"inotify_add_watch",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"pathname", 4},
             [ARG_2] = {"mask", 4},
     }},
    {"inotify_init", 316, NORMAL, {}},
    {"inotify_init1",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"flags", 4},
     }},
    {"inotify_rm_watch",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"wd", 4},
     }},
    {"io_cancel",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ctx_id", 4}, [ARG_1] = {"iocb", 4},
             [ARG_2] = {"result", 4},
     }},
    {"ioctl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"cmd", 4}, [ARG_2] = {"arg", 4},
     }},
    {"io_destroy",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ctx", 4},
     }},
    {"io_getevents",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ctx_id", 4}, [ARG_1] = {"min_nr", 4},
             [ARG_2] = {"nr", 4}, [ARG_3] = {"events", 4},
             [ARG_4] = {"timeout", 4},
     }},
    {"ioprio_get",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which", 4}, [ARG_1] = {"who", 4},
     }},
    {"ioprio_set",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which", 4}, [ARG_1] = {"who", 4},
             [ARG_2] = {"ioprio", 4},
     }},
    {"io_setup",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"nr_events", 4}, [ARG_1] = {"ctxp", 4},
     }},
    {"io_submit",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ctx_id", 4}, [ARG_1] = {"nr", 4},
             [ARG_2] = {"iocbpp", 4},
     }},
    {"ipc",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"call", 4}, [ARG_1] = {"first", 4},
             [ARG_2] = {"second", 4}, [ARG_3] = {"third", 4},
             [ARG_4] = {"ptr", 4}, [ARG_5] = {"fifth", 4},
     }},  // obsolete, no longer available for EABI
    {"kcmp",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid1", 4}, [ARG_1] = {"pid2", 4},
             [ARG_2] = {"type", 4}, [ARG_3] = {"idx1", 4},
             [ARG_4] = {"idx2", 4},
     }},
    {"kexec_load",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"entry", 4}, [ARG_1] = {"nr_segments", 4},
             [ARG_2] = {"segments", 4}, [ARG_3] = {"flags", 4},
     }},
    {"keyctl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"option", 4}, [ARG_1] = {"arg2", 4},
             [ARG_2] = {"arg3", 4}, [ARG_3] = {"arg4", 4},
             [ARG_4] = {"arg5", 4},
     }},
    {"kill",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"sig", 4},
     }},
    {"lchown",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 4}, [ARG_1] = {"user", 4},
             [ARG_2] = {"group", 4},
     }},
    {"lchown16",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 4}, [ARG_1] = {"user", 2},
             [ARG_2] = {"group", 2},
     }},
    {"lgetxattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 4}, [ARG_1] = {"name", 4},
             [ARG_2] = {"value", 4}, [ARG_3] = {"size", 4},
     }},
    {"link",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"oldname", 4}, [ARG_1] = {"newname", 4},
     }},
    {"linkat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"olddfd", 4}, [ARG_1] = {"oldname", 4},
             [ARG_2] = {"newdfd", 4}, [ARG_3] = {"newname", 4},
             [ARG_4] = {"flags", 4},
     }},
    {"listen",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"backlog", 4},
     }},
    {"listxattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 4}, [ARG_1] = {"list", 4},
             [ARG_2] = {"size", 4},
     }},
    {"llistxattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 4}, [ARG_1] = {"list", 4},
             [ARG_2] = {"size", 4},
     }},
    {"llseek",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"offset_high", 4},
             [ARG_2] = {"offset_low", 4}, [ARG_3] = {"result", 4},
             [ARG_4] = {"whence", 4},
     }},
    {"lookup_dcookie",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"cookie64", 8}, [ARG_1] = {"buf", 4},
             [ARG_2] = {"len", 4},
     }},
    {"lremovexattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 4}, [ARG_1] = {"name", 4},
     }},
    {"lseek",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"offset", 4},
             [ARG_2] = {"whence", 4},
     }},
    {"lsetxattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 4}, [ARG_1] = {"name", 4},
             [ARG_2] = {"value", 4}, [ARG_3] = {"size", 4},
             [ARG_4] = {"flags", 4},
     }},
    {"lstat64",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 4}, [ARG_1] = {"statbuf", 4},
     }},
    {"madvise",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"start", 4}, [ARG_1] = {"len_in", 4},
             [ARG_2] = {"behavior", 4},
     }},
    {"mbind",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"start", 4}, [ARG_1] = {"len", 4},
             [ARG_2] = {"mode", 4}, [ARG_3] = {"nmask", 4},
             [ARG_4] = {"maxnode", 4}, [ARG_5] = {"flags", 4},
     }},
    {"membarrier",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"cmd", 4}, [ARG_1] = {"flags", 4},
     }},
    {"memfd_create",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"uname", 4}, [ARG_1] = {"flags", 4},
     }},
    {"mincore",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"start", 4}, [ARG_1] = {"len", 4}, [ARG_2] = {"vec", 4},
     }},
    {"mkdir",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 4}, [ARG_1] = {"mode", 2},
     }},
    {"mkdirat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"pathname", 4},
             [ARG_2] = {"mode", 2},
     }},
    {"mknod",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 4}, [ARG_1] = {"mode", 2},
             [ARG_2] = {"dev", 4},
     }},
    {"mknodat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"filename", 4},
             [ARG_2] = {"mode", 2}, [ARG_3] = {"dev", 4},
     }},
    {"mlock",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"start", 4}, [ARG_1] = {"len", 4},
     }},
    {"mlock2",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"start", 4}, [ARG_1] = {"len", 4},
             [ARG_2] = {"flags", 4},
     }},
    {"mlockall",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"flags", 4},
     }},
    {"mmap",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"addr", 4}, [ARG_1] = {"len", 4}, [ARG_2] = {"prot", 4},
             [ARG_3] = {"flags", 4}, [ARG_4] = {"fd", 4},
             [ARG_5] = {"offset", 4},
     }},  // obsolete, no longer available for EABI
    {"mmap2",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"addr", 4}, [ARG_1] = {"len", 4}, [ARG_2] = {"prot", 4},
             [ARG_3] = {"flags", 4}, [ARG_4] = {"fd", 4},
             [ARG_5] = {"pgoffset", 4},
     }},
    {"mount",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dev_name", 4}, [ARG_1] = {"dir_name", 4},
             [ARG_2] = {"type", 4}, [ARG_3] = {"flags", 4},
             [ARG_4] = {"data", 4},
     }},
    {"move_pages",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"nr_pages", 4},
             [ARG_2] = {"pages", 4}, [ARG_3] = {"nodes", 4},
             [ARG_4] = {"status", 4}, [ARG_5] = {"flag", 4},
     }},
    {"mprotect",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"start", 4}, [ARG_1] = {"len", 4},
             [ARG_2] = {"prot", 4},
     }},
    {"mq_getsetattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"mqdes", 4}, [ARG_1] = {"u_mqstat", 4},
             [ARG_2] = {"u_omqstat", 4},
     }},
    {"mq_notify",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"mqdes", 4}, [ARG_1] = {"u_notification", 4},
     }},
    {"mq_open",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"u_name", 4}, [ARG_1] = {"oflag", 4},
             [ARG_2] = {"mode", 2}, [ARG_3] = {"u_attr", 4},
     }},
    {"mq_timedreceive",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"mqdes", 4}, [ARG_1] = {"u_msg_ptr", 4},
             [ARG_2] = {"msg_len", 4}, [ARG_3] = {"u_msg_prio", 4},
             [ARG_4] = {"u_abs_timeout", 4},
     }},
    {"mq_timedsend",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"mqdes", 4}, [ARG_1] = {"u_msg_ptr", 4},
             [ARG_2] = {"msg_len", 4}, [ARG_3] = {"msg_prio", 4},
             [ARG_4] = {"u_abs_timeout", 4},
     }},
    {"mq_unlink",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"u_name", 4},
     }},
    {"mremap",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"addr", 4}, [ARG_1] = {"old_len", 4},
             [ARG_2] = {"new_len", 4}, [ARG_3] = {"flags", 4},
             [ARG_4] = {"new_addr", 4},
     }},
    {"msgctl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"msqid", 4}, [ARG_1] = {"cmd", 4}, [ARG_2] = {"buf", 4},
     }},
    {"msgget",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"key", 4}, [ARG_1] = {"msgflg", 4},
     }},
    {"msgrcv",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"msqid", 4}, [ARG_1] = {"msgp", 4},
             [ARG_2] = {"msgsz", 4}, [ARG_3] = {"msgtyp", 4},
             [ARG_4] = {"msgflg", 4},
     }},
    {"msgsnd",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"msqid", 4}, [ARG_1] = {"msgp", 4},
             [ARG_2] = {"msgsz", 4}, [ARG_3] = {"msgflg", 4},
     }},
    {"msync",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"start", 4}, [ARG_1] = {"len", 4},
             [ARG_2] = {"flags", 4},
     }},
    {"munlock",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"start", 4}, [ARG_1] = {"len", 4},
     }},
    {"munlockall", 153, NORMAL, {}},
    {"munmap",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"addr", 4}, [ARG_1] = {"len", 4},
     }},
    {"name_to_handle_at",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"name", 4},
             [ARG_2] = {"handle", 4}, [ARG_3] = {"mnt_id", 4},
             [ARG_4] = {"flag", 4},
     }},
    {"nanosleep",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"rqtp", 4}, [ARG_1] = {"rmtp", 4},
     }},
    {"newfstat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"statbuf", 4},
     }},
    {"newlstat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 4}, [ARG_1] = {"statbuf", 4},
     }},
    {"newstat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 4}, [ARG_1] = {"statbuf", 4},
     }},
    {"newuname",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"name", 4},
     }},
    {"nfsservctl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"cmd", 4}, [ARG_1] = {"argp", 4}, [ARG_2] = {"resp", 4},
     }},
    {"nice",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"increment", 4},
     }},
    {"old_getrlimit",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"resource", 4}, [ARG_1] = {"rlim", 4},
     }},
    {"old_oldumount",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"name", 4},
     }},
    {"old_select",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"arg", 4},
     }},
    {"open",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 4}, [ARG_1] = {"flags", 4},
             [ARG_2] = {"mode", 2},
     }},
    {"openat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"filename", 4},
             [ARG_2] = {"flags", 4}, [ARG_3] = {"mode", 2},
     }},
    {"open_by_handle_at",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"mountdirfd", 4}, [ARG_1] = {"handle", 4},
             [ARG_2] = {"flags", 4},
     }},
    {"pause", 29, NORMAL, {}},
    {"pciconfig_iobase",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which", 4}, [ARG_1] = {"bus", 4},
             [ARG_2] = {"devfn", 4},
     }},
    {"pciconfig_read",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"bus", 4}, [ARG_1] = {"dfn", 4}, [ARG_2] = {"off", 4},
             [ARG_3] = {"len", 4}, [ARG_4] = {"buf", 4},
     }},
    {"pciconfig_write",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"bus", 4}, [ARG_1] = {"dfn", 4}, [ARG_2] = {"off", 4},
             [ARG_3] = {"len", 4}, [ARG_4] = {"buf", 4},
     }},
    {"perf_event_open",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"attr_uptr", 4}, [ARG_1] = {"pid", 4},
             [ARG_2] = {"cpu", 4}, [ARG_3] = {"group_fd", 4},
             [ARG_4] = {"flags", 4},
     }},
    {"personality",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"personality", 4},
     }},
    {"pipe",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fildes", 4},
     }},
    {"pipe2",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fildes", 4}, [ARG_1] = {"flags", 4},
     }},
    {"pivot_root",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"new_root", 4}, [ARG_1] = {"put_old", 4},
     }},
    {"poll",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ufds", 4}, [ARG_1] = {"nfds", 4},
             [ARG_2] = {"timeout_msecs", 4},
     }},
    {"ppoll",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ufds", 4}, [ARG_1] = {"nfds", 4}, [ARG_2] = {"tsp", 4},
             [ARG_3] = {"sigmask", 4}, [ARG_4] = {"sigsetsize", 4},
     }},
    {"prctl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"option", 4}, [ARG_1] = {"arg2", 4},
             [ARG_2] = {"arg3", 4}, [ARG_3] = {"arg4", 4},
             [ARG_4] = {"arg5", 4},
     }},
    {"pread64",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"buf", 4}, [ARG_2] = {"count", 4},
             [ARG_3] = {"pos", 8},
     }},
    {"preadv",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"vec", 4}, [ARG_2] = {"vlen", 4},
             [ARG_3] = {"pos_l", 4}, [ARG_4] = {"pos_h", 4},
     }},
    {"preadv2",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"vec", 4}, [ARG_2] = {"vlen", 4},
             [ARG_3] = {"pos_l", 4}, [ARG_4] = {"pos_h", 4},
             [ARG_5] = {"flags", 4},
     }},
    {"prlimit64",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"resource", 4},
             [ARG_2] = {"new_rlim", 4}, [ARG_3] = {"old_rlim", 4},
     }},
    {"process_vm_readv",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"lvec", 4},
             [ARG_2] = {"liovcnt", 4}, [ARG_3] = {"rvec", 4},
             [ARG_4] = {"riovcnt", 4}, [ARG_5] = {"flags", 4},
     }},
    {"process_vm_writev",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"lvec", 4},
             [ARG_2] = {"liovcnt", 4}, [ARG_3] = {"rvec", 4},
             [ARG_4] = {"riovcnt", 4}, [ARG_5] = {"flags", 4},
     }},
    {"pselect6",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"n", 4}, [ARG_1] = {"inp", 4}, [ARG_2] = {"outp", 4},
             [ARG_3] = {"exp", 4}, [ARG_4] = {"tsp", 4}, [ARG_5] = {"sig", 4},
     }},
    {"ptrace",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"request", 4}, [ARG_1] = {"pid", 4},
             [ARG_2] = {"addr", 4}, [ARG_3] = {"data", 4},
     }},
    {"pwrite64",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"buf", 4}, [ARG_2] = {"count", 4},
             [ARG_3] = {"pos", 8},
     }},
    {"pwritev",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"vec", 4}, [ARG_2] = {"vlen", 4},
             [ARG_3] = {"pos_l", 4}, [ARG_4] = {"pos_h", 4},
     }},
    {"pwritev2",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"vec", 4}, [ARG_2] = {"vlen", 4},
             [ARG_3] = {"pos_l", 4}, [ARG_4] = {"pos_h", 4},
             [ARG_5] = {"flags", 4},
     }},
    {"quotactl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"cmd", 4}, [ARG_1] = {"special", 4},
             [ARG_2] = {"id", 4}, [ARG_3] = {"addr", 4},
     }},
    {"read",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"buf", 4}, [ARG_2] = {"count", 4},
     }},
    {"readahead",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"offset", 8},
             [ARG_2] = {"count", 4},
     }},
    {"readdir",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"dirent", 4},
             [ARG_2] = {"count", 4},
     }},  // obsolete, no longer available for EABI
    {"readlink",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"path", 4}, [ARG_1] = {"buf", 4},
             [ARG_2] = {"bufsiz", 4},
     }},
    {"readlinkat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"pathname", 4},
             [ARG_2] = {"buf", 4}, [ARG_3] = {"bufsiz", 4},
     }},
    {"readv",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"vec", 4}, [ARG_2] = {"vlen", 4},
     }},
    {"reboot",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"magic1", 4}, [ARG_1] = {"magic2", 4},
             [ARG_2] = {"cmd", 4}, [ARG_3] = {"arg", 4},
     }},
    {"recv",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"ubuf", 4}, [ARG_2] = {"size", 4},
             [ARG_3] = {"flags", 4},
     }},
    {"recvfrom",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"ubuf", 4}, [ARG_2] = {"size", 4},
             [ARG_3] = {"flags", 4}, [ARG_4] = {"addr", 4},
             [ARG_5] = {"addr_len", 4},
     }},
    {"recvmmsg",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"mmsg", 4}, [ARG_2] = {"vlen", 4},
             [ARG_3] = {"flags", 4}, [ARG_4] = {"timeout", 4},
     }},
    {"recvmsg",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"msg", 4}, [ARG_2] = {"flags", 4},
     }},
    {"remap_file_pages",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"start", 4}, [ARG_1] = {"size", 4},
             [ARG_2] = {"prot", 4}, [ARG_3] = {"pgoff", 4},
             [ARG_4] = {"flags", 4},
     }},
    {"removexattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 4}, [ARG_1] = {"name", 4},
     }},
    {"rename",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"oldname", 4}, [ARG_1] = {"newname", 4},
     }},
    {"renameat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"olddfd", 4}, [ARG_1] = {"oldname", 4},
             [ARG_2] = {"newdfd", 4}, [ARG_3] = {"newname", 4},
     }},
    {"renameat2",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"olddfd", 4}, [ARG_1] = {"oldname", 4},
             [ARG_2] = {"newdfd", 4}, [ARG_3] = {"newname", 4},
             [ARG_4] = {"flags", 4},
     }},
    {"request_key",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"_type", 4}, [ARG_1] = {"_description", 4},
             [ARG_2] = {"_callout_info", 4}, [ARG_3] = {"destringid", 4},
     }},
    {"restart_syscall", 0, NORMAL, {}},
    {"rmdir",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 4},
     }},
    {"rt_sigaction",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"sig", 4}, [ARG_1] = {"act", 4}, [ARG_2] = {"oact", 4},
             [ARG_3] = {"sigsetsize", 4},
     }},
    {"rt_sigpending",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"uset", 4}, [ARG_1] = {"sigsetsize", 4},
     }},
    {"rt_sigprocmask",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"how", 4}, [ARG_1] = {"nset", 4}, [ARG_2] = {"oset", 4},
             [ARG_3] = {"sigsetsize", 4},
     }},
    {"rt_sigqueueinfo",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"sig", 4}, [ARG_2] = {"uinfo", 4},
     }},
    {"rt_sigreturn", 173, NORMAL, {}},
    {"rt_sigsuspend",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"unewset", 4}, [ARG_1] = {"sigsetsize", 4},
     }},
    {"rt_sigtimedwait",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"uthese", 4}, [ARG_1] = {"uinfo", 4},
             [ARG_2] = {"uts", 4}, [ARG_3] = {"sigsetsize", 4},
     }},
    {"rt_tgsigqueueinfo",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"tgid", 4}, [ARG_1] = {"pid", 4}, [ARG_2] = {"sig", 4},
             [ARG_3] = {"uinfo", 4},
     }},
    {"sched_getaffinity",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"len", 4},
             [ARG_2] = {"user_mask_ptr", 4},
     }},
    {"sched_getattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"uattr", 4},
             [ARG_2] = {"size", 4}, [ARG_3] = {"flags", 4},
     }},
    {"sched_getparam",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"param", 4},
     }},
    {"sched_get_priority_max",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"policy", 4},
     }},
    {"sched_get_priority_min",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"policy", 4},
     }},
    {"sched_getscheduler",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4},
     }},
    {"sched_rr_get_interval",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"interval", 4},
     }},
    {"sched_setaffinity",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"len", 4},
             [ARG_2] = {"user_mask_ptr", 4},
     }},
    {"sched_setattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"uattr", 4},
             [ARG_2] = {"flags", 4},
     }},
    {"sched_setparam",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"param", 4},
     }},
    {"sched_setscheduler",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"policy", 4},
             [ARG_2] = {"param", 4},
     }},
    {"sched_yield", 158, NORMAL, {}},
    {"seccomp",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"op", 4}, [ARG_1] = {"flags", 4},
             [ARG_2] = {"uargs", 4},
     }},
    {"select",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"n", 4}, [ARG_1] = {"inp", 4}, [ARG_2] = {"outp", 4},
             [ARG_3] = {"exp", 4}, [ARG_4] = {"tvp", 4},
     }},
    {"semctl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"semid", 4}, [ARG_1] = {"semnum", 4},
             [ARG_2] = {"cmd", 4}, [ARG_3] = {"arg", 4},
     }},
    {"semget",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"key", 4}, [ARG_1] = {"nsems", 4},
             [ARG_2] = {"semflg", 4},
     }},
    {"semop",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"semid", 4}, [ARG_1] = {"tsops", 4},
             [ARG_2] = {"nsops", 4},
     }},
    {"semtimedop",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"semid", 4}, [ARG_1] = {"tsops", 4},
             [ARG_2] = {"nsops", 4}, [ARG_3] = {"timeout", 4},
     }},
    {"send",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"buff", 4}, [ARG_2] = {"len", 4},
             [ARG_3] = {"flags", 4},
     }},
    {"sendfile",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"out_fd", 4}, [ARG_1] = {"in_fd", 4},
             [ARG_2] = {"offset", 4}, [ARG_3] = {"count", 4},
     }},
    {"sendfile64",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"out_fd", 4}, [ARG_1] = {"in_fd", 4},
             [ARG_2] = {"offset", 4}, [ARG_3] = {"count", 4},
     }},
    {"sendmmsg",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"mmsg", 4}, [ARG_2] = {"vlen", 4},
             [ARG_3] = {"flags", 4},
     }},
    {"sendmsg",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"msg", 4}, [ARG_2] = {"flags", 4},
     }},
    {"sendto",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"buff", 4}, [ARG_2] = {"len", 4},
             [ARG_3] = {"flags", 4}, [ARG_4] = {"addr", 4},
             [ARG_5] = {"addr_len", 4},
     }},
    {"setdomainname",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"name", 4}, [ARG_1] = {"len", 4},
     }},
    {"setfsgid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"gid", 4},
     }},
    {"setfsgid16",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"gid", 2},
     }},
    {"setfsuid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"uid", 4},
     }},
    {"setfsuid16",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"uid", 2},
     }},
    {"setgid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"gid", 4},
     }},
    {"setgid16",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"gid", 2},
     }},
    {"setgroups",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"gidsetsize", 4}, [ARG_1] = {"grouplist", 4},
     }},
    {"setgroups16",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"gidsetsize", 4}, [ARG_1] = {"grouplist", 4},
     }},
    {"sethostname",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"name", 4}, [ARG_1] = {"len", 4},
     }},
    {"setitimer",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which", 4}, [ARG_1] = {"value", 4},
             [ARG_2] = {"ovalue", 4},
     }},
    {"set_mempolicy",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"mode", 4}, [ARG_1] = {"nmask", 4},
             [ARG_2] = {"maxnode", 4},
     }},
    {"setns",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"nstype", 4},
     }},
    {"setpgid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"pgid", 4},
     }},
    {"setpriority",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which", 4}, [ARG_1] = {"who", 4},
             [ARG_2] = {"niceval", 4},
     }},
    {"setregid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"rgid", 4}, [ARG_1] = {"egid", 4},
     }},
    {"setregid16",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"rgid", 2}, [ARG_1] = {"egid", 2},
     }},
    {"setresgid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"rgid", 4}, [ARG_1] = {"egid", 4},
             [ARG_2] = {"sgid", 4},
     }},
    {"setresgid16",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"rgid", 2}, [ARG_1] = {"egid", 2},
             [ARG_2] = {"sgid", 2},
     }},
    {"setresuid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ruid", 4}, [ARG_1] = {"euid", 4},
             [ARG_2] = {"suid", 4},
     }},
    {"setresuid16",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ruid", 2}, [ARG_1] = {"euid", 2},
             [ARG_2] = {"suid", 2},
     }},
    {"setreuid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ruid", 4}, [ARG_1] = {"euid", 4},
     }},
    {"setreuid16",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ruid", 2}, [ARG_1] = {"euid", 2},
     }},
    {"setrlimit",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"resource", 4}, [ARG_1] = {"rlim", 4},
     }},
    {"set_robust_list",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"head", 4}, [ARG_1] = {"len", 4},
     }},
    {"setsid", 66, NORMAL, {}},
    {"setsockopt",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"level", 4},
             [ARG_2] = {"optname", 4}, [ARG_3] = {"optval", 4},
             [ARG_4] = {"optlen", 4},
     }},
    {"set_tid_address",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"tidptr", 4},
     }},
    {"settimeofday",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"tv", 4}, [ARG_1] = {"tz", 4},
     }},
    {"set_tls",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"val", 4},
     }},
    {"setuid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"uid", 4},
     }},
    {"setuid16",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"uid", 2},
     }},
    {"setxattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 4}, [ARG_1] = {"name", 4},
             [ARG_2] = {"value", 4}, [ARG_3] = {"size", 4},
             [ARG_4] = {"flags", 4},
     }},
    {"shmat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"shmid", 4}, [ARG_1] = {"shmaddr", 4},
             [ARG_2] = {"shmflg", 4},
     }},
    {"shmctl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"shmid", 4}, [ARG_1] = {"cmd", 4}, [ARG_2] = {"buf", 4},
     }},
    {"shmdt",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"shmaddr", 4},
     }},
    {"shmget",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"key", 4}, [ARG_1] = {"size", 4},
             [ARG_2] = {"shmflg", 4},
     }},
    {"shutdown",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"how", 4},
     }},
    {"sigaction",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"sig", 4}, [ARG_1] = {"act", 4}, [ARG_2] = {"oact", 4},
     }},
    {"sigaltstack",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"uss", 4}, [ARG_1] = {"uoss", 4},
     }},
    {"signalfd",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ufd", 4}, [ARG_1] = {"user_mask", 4},
             [ARG_2] = {"sizemask", 4},
     }},
    {"signalfd4",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ufd", 4}, [ARG_1] = {"user_mask", 4},
             [ARG_2] = {"sizemask", 4}, [ARG_3] = {"flags", 4},
     }},
    {"sigpending",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"set", 4},
     }},
    {"sigprocmask",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"how", 4}, [ARG_1] = {"nset", 4}, [ARG_2] = {"oset", 4},
     }},
    {"sigreturn", 119, NORMAL, {}},
    {"sigsuspend",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"unused1", 4}, [ARG_1] = {"unused2", 4},
             [ARG_2] = {"mask", 4},
     }},
    {"socket",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"family", 4}, [ARG_1] = {"type", 4},
             [ARG_2] = {"protocol", 4},
     }},
    {"socketcall",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"call", 4}, [ARG_1] = {"args", 4},
     }},  // obsolete, no longer available for EABI
    {"socketpair",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"family", 4}, [ARG_1] = {"type", 4},
             [ARG_2] = {"protocol", 4}, [ARG_3] = {"usockvec", 4},
     }},
    {"splice",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd_in", 4}, [ARG_1] = {"off_in", 4},
             [ARG_2] = {"fd_out", 4}, [ARG_3] = {"off_out", 4},
             [ARG_4] = {"len", 4}, [ARG_5] = {"flags", 4},
     }},
    {"stat64",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 4}, [ARG_1] = {"statbuf", 4},
     }},
    {"statfs",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 4}, [ARG_1] = {"buf", 4},
     }},
    {"statfs64",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"path", 4}, [ARG_1] = {"sz", 4}, [ARG_2] = {"buf", 4},
     }},
    {"stime",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"tptr", 4},
     }},  // obsolete, no longer available for EABI
    {"swapoff",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"specialfile", 4},
     }},
    {"swapon",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"specialfile", 4}, [ARG_1] = {"swap_flags", 4},
     }},
    {"symlink",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"oldname", 4}, [ARG_1] = {"newname", 4},
     }},
    {"symlinkat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"oldname", 4}, [ARG_1] = {"newdfd", 4},
             [ARG_2] = {"newname", 4},
     }},
    {"sync", 36, NORMAL, {}},
    {"sync_file_range2",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"flags", 4},
             [ARG_2] = {"offset", 8}, [ARG_3] = {"nbytes", 8},
     }},
    {"syncfs",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4},
     }},
    {"syscall", 113, NORMAL, {}},  // obsolete, no longer available for EABI
    {"sysctl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"args", 4},
     }},
    {"sysfs",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"option", 4}, [ARG_1] = {"arg1", 4},
             [ARG_2] = {"arg2", 4},
     }},
    {"sysinfo",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"info", 4},
     }},
    {"syslog",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"type", 4}, [ARG_1] = {"buf", 4}, [ARG_2] = {"len", 4},
     }},
    {"tee",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fdin", 4}, [ARG_1] = {"fdout", 4},
             [ARG_2] = {"len", 4}, [ARG_3] = {"flags", 4},
     }},
    {"tgkill",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"tgid", 4}, [ARG_1] = {"pid", 4}, [ARG_2] = {"sig", 4},
     }},
    {"time",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"tloc", 4},
     }},  // obsolete, no longer available for EABI
    {"timer_create",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which_clock", 4}, [ARG_1] = {"timer_event_spec", 4},
             [ARG_2] = {"created_timer_id", 4},
     }},
    {"timer_delete",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"timer_id", 4},
     }},
    {"timerfd_create",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"clockid", 4}, [ARG_1] = {"flags", 4},
     }},
    {"timerfd_gettime",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ufd", 4}, [ARG_1] = {"otmr", 4},
     }},
    {"timerfd_settime",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ufd", 4}, [ARG_1] = {"flags", 4},
             [ARG_2] = {"utmr", 4}, [ARG_3] = {"otmr", 4},
     }},
    {"timer_getoverrun",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"timer_id", 4},
     }},
    {"timer_gettime",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"timer_id", 4}, [ARG_1] = {"setting", 4},
     }},
    {"timer_settime",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"timer_id", 4}, [ARG_1] = {"flags", 4},
             [ARG_2] = {"new_setting", 4}, [ARG_3] = {"old_setting", 4},
     }},
    {"times",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"tbuf", 4},
     }},
    {"tkill",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"sig", 4},
     }},
    {"truncate",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"path", 4}, [ARG_1] = {"length", 4},
     }},
    {"truncate64",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"path", 4}, [ARG_1] = {"length", 8},
     }},
    {"umask",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"mask", 4},
     }},
    {"umount",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"name", 4}, [ARG_1] = {"flags", 4},
     }},
    {"unlink",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 4},
     }},
    {"unlinkat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"pathname", 4},
             [ARG_2] = {"flag", 4},
     }},
    {"unshare",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"unshare_flags", 4},
     }},
    {"uselib",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"library", 4},
     }},
    {"userfaultfd",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"flags", 4},
     }},
    {"usr26", 983043, NORMAL, {}},
    {"usr32", 983044, NORMAL, {}},
    {"ustat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dev", 4}, [ARG_1] = {"ubuf", 4},
     }},
    {"utime",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 4}, [ARG_1] = {"times", 4},
     }},
    {"utimensat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"filename", 4},
             [ARG_2] = {"utimes", 4}, [ARG_3] = {"flags", 4},
     }},
    {"utimes",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 4}, [ARG_1] = {"utimes", 4},
     }},
    {"vfork", 190, NORMAL, {}},
    {"vhangup", 111, NORMAL, {}},
    {"vmsplice",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"iov", 4},
             [ARG_2] = {"nr_segs", 4}, [ARG_3] = {"flags", 4},
     }},
    {"vserver", 313, NORMAL, {}},  // unimplemented system call
    {"wait4",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"upid", 4}, [ARG_1] = {"stat_addr", 4},
             [ARG_2] = {"options", 4}, [ARG_3] = {"ru", 4},
     }},
    {"waitid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which", 4}, [ARG_1] = {"upid", 4},
             [ARG_2] = {"infop", 4}, [ARG_3] = {"options", 4},
             [ARG_4] = {"ru", 4},
     }},
    {"write",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"buf", 4}, [ARG_2] = {"count", 4},
     }},
    {"writev",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"vec", 4}, [ARG_2] = {"vlen", 4},
     }},
};




const size_t TEMPLATE_ARCH_syscall_list_size =
    sizeof(TEMPLATE_ARCH_syscall_list) / sizeof(TEMPLATE_ARCH_syscall_list[0]);
