/*
   Kafel - syscalls (TEMPLATE_ARCH)
   -----------------------------------------

   Copyright 2016 Google Inc. All Rights Reserved.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

*/

#include "../syscall.h"

#include <stddef.h>

#define ARG_0 0
#define ARG_1 1
#define ARG_2 2
#define ARG_3 3
#define ARG_4 4
#define ARG_5 5

#define NORMAL false

const struct syscall_descriptor TEMPLATE_ARCH_syscall_list[] = {
    {"accept",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"upeer_sockaddr", 8},
             [ARG_2] = {"upeer_addrlen", 8},
     }},
    {"accept4",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"upeer_sockaddr", 8},
             [ARG_2] = {"upeer_addrlen", 8}, [ARG_3] = {"flags", 4},
     }},
    {"access",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 8}, [ARG_1] = {"mode", 4},
     }},
    {"acct",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"name", 8},
     }},
    {"add_key",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"_type", 8}, [ARG_1] = {"_description", 8},
             [ARG_2] = {"_payload", 8}, [ARG_3] = {"plen", 8},
             [ARG_4] = {"ringid", 4},
     }},
    {"adjtimex",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"txc_p", 8},
     }},
    {"afs_syscall", TEMPLATE_NUM, NORMAL, {}},  // Unimplemented system call
    {"alarm",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"seconds", 4},
     }},
    {"arch_prctl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"code", 4}, [ARG_1] = {"addr", 8},
     }},
    {"bind",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"umyaddr", 8},
             [ARG_2] = {"addrlen", 4},
     }},
    {"bpf",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"cmd", 4}, [ARG_1] = {"uattr", 8},
             [ARG_2] = {"size", 4},
     }},
    {"brk",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"brk", 8},
     }},
    {"capget",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"header", 8}, [ARG_1] = {"dataptr", 8},
     }},
    {"capset",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"header", 8}, [ARG_1] = {"data", 8},
     }},
    {"chdir",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 8},
     }},
    {"chmod",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 8}, [ARG_1] = {"mode", 2},
     }},
    {"chown",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 8}, [ARG_1] = {"user", 4},
             [ARG_2] = {"group", 4},
     }},
    {"chroot",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 8},
     }},
    {"clock_adjtime",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which_clock", 4}, [ARG_1] = {"utx", 8},
     }},
    {"clock_getres",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which_clock", 4}, [ARG_1] = {"tp", 8},
     }},
    {"clock_gettime",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which_clock", 4}, [ARG_1] = {"tp", 8},
     }},
    {"clock_nanosleep",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which_clock", 4}, [ARG_1] = {"flags", 4},
             [ARG_2] = {"rqtp", 8}, [ARG_3] = {"rmtp", 8},
     }},
    {"clock_settime",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which_clock", 4}, [ARG_1] = {"tp", 8},
     }},
    {"clone",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"clone_flags", 8}, [ARG_1] = {"newsp", 8},
             [ARG_2] = {"parent_tidptr", 8}, [ARG_3] = {"child_tidptr", 8},
             [ARG_4] = {"tls", 8},
     }},
    {"close",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4},
     }},
    {"connect",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"uservaddr", 8},
             [ARG_2] = {"addrlen", 4},
     }},
    {"copy_file_range",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd_in", 4}, [ARG_1] = {"off_in", 8},
             [ARG_2] = {"fd_out", 4}, [ARG_3] = {"off_out", 8},
             [ARG_4] = {"len", 8}, [ARG_5] = {"flags", 4},
     }},
    {"creat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 8}, [ARG_1] = {"mode", 2},
     }},
    {"create_module",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"name", 8}, [ARG_1] = {"size", 8},
     }},  // only in kernels before Linux 2.6
    {"delete_module",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"name_user", 8}, [ARG_1] = {"flags", 4},
     }},
    {"dup",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fildes", 4},
     }},
    {"dup2",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"oldfd", 4}, [ARG_1] = {"newfd", 4},
     }},
    {"dup3",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"oldfd", 4}, [ARG_1] = {"newfd", 4},
             [ARG_2] = {"flags", 4},
     }},
    {"epoll_create",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"size", 4},
     }},
    {"epoll_create1",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"flags", 4},
     }},
    {"epoll_ctl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"epfd", 4}, [ARG_1] = {"op", 4}, [ARG_2] = {"fd", 4},
             [ARG_3] = {"event", 8},
     }},
    {"epoll_ctl_old", TEMPLATE_NUM, NORMAL, {}},  // old/Unimplemented system call
    {"epoll_pwait",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"epfd", 4}, [ARG_1] = {"events", 8},
             [ARG_2] = {"maxevents", 4}, [ARG_3] = {"timeout", 4},
             [ARG_4] = {"sigmask", 8}, [ARG_5] = {"sigsetsize", 8},
     }},
    {"epoll_wait",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"epfd", 4}, [ARG_1] = {"events", 8},
             [ARG_2] = {"maxevents", 4}, [ARG_3] = {"timeout", 4},
     }},
    {"epoll_wait_old", TEMPLATE_NUM, NORMAL, {}},  // old/Unimplemented system call
    {"eventfd",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"count", 4},
     }},
    {"eventfd2",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"count", 4}, [ARG_1] = {"flags", 4},
     }},
    {"execve",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 8}, [ARG_1] = {"argv", 8},
             [ARG_2] = {"envp", 8},
     }},
    {"execveat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"filename", 8},
             [ARG_2] = {"argv", 8}, [ARG_3] = {"envp", 8},
             [ARG_4] = {"flags", 4},
     }},
    {"exit",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"error_code", 4},
     }},
    {"exit_group",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"error_code", 4},
     }},
    {"faccessat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"filename", 8},
             [ARG_2] = {"mode", 4},
     }},
    {"fadvise64",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"offset", 8}, [ARG_2] = {"len", 8},
             [ARG_3] = {"advice", 4},
     }},
    {"fallocate",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"mode", 4},
             [ARG_2] = {"offset", 8}, [ARG_3] = {"len", 8},
     }},
    {"fanotify_init",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"flags", 4}, [ARG_1] = {"event_f_flags", 4},
     }},
    {"fanotify_mark",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fanotify_fd", 4}, [ARG_1] = {"flags", 4},
             [ARG_2] = {"mask", 8}, [ARG_3] = {"dfd", 4},
             [ARG_4] = {"pathname", 8},
     }},
    {"fchdir",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4},
     }},
    {"fchmod",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"mode", 2},
     }},
    {"fchmodat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"filename", 8},
             [ARG_2] = {"mode", 2},
     }},
    {"fchown",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"user", 4}, [ARG_2] = {"group", 4},
     }},
    {"fchownat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"filename", 8},
             [ARG_2] = {"user", 4}, [ARG_3] = {"group", 4},
             [ARG_4] = {"flag", 4},
     }},
    {"fcntl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"cmd", 4}, [ARG_2] = {"arg", 8},
     }},
    {"fdatasync",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4},
     }},
    {"fgetxattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"name", 8}, [ARG_2] = {"value", 8},
             [ARG_3] = {"size", 8},
     }},
    {"finit_module",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"uargs", 8},
             [ARG_2] = {"flags", 4},
     }},
    {"flistxattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"list", 8}, [ARG_2] = {"size", 8},
     }},
    {"flock",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"cmd", 4},
     }},
    {"fork", TEMPLATE_NUM, NORMAL, {}},
    {"fremovexattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"name", 8},
     }},
    {"fsetxattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"name", 8}, [ARG_2] = {"value", 8},
             [ARG_3] = {"size", 8}, [ARG_4] = {"flags", 4},
     }},
    {"fstatfs",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"buf", 8},
     }},
    {"fsync",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4},
     }},
    {"ftruncate",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"length", 8},
     }},
    {"futex",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"uaddr", 8}, [ARG_1] = {"op", 4}, [ARG_2] = {"val", 4},
             [ARG_3] = {"utime", 8}, [ARG_4] = {"uaddr2", 8},
             [ARG_5] = {"val3", 4},
     }},
    {"futimesat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"filename", 8},
             [ARG_2] = {"utimes", 8},
     }},
    {"getcpu",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"cpup", 8}, [ARG_1] = {"nodep", 8},
             [ARG_2] = {"unused", 8},
     }},
    {"getcwd",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"buf", 8}, [ARG_1] = {"size", 8},
     }},
    {"getdents",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"dirent", 8},
             [ARG_2] = {"count", 4},
     }},
    {"getdents64",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"dirent", 8},
             [ARG_2] = {"count", 4},
     }},
    {"getegid", TEMPLATE_NUM, NORMAL, {}},
    {"geteuid", TEMPLATE_NUM, NORMAL, {}},
    {"getgid", TEMPLATE_NUM, NORMAL, {}},
    {"getgroups",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"gidsetsize", 4}, [ARG_1] = {"grouplist", 8},
     }},
    {"getitimer",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which", 4}, [ARG_1] = {"value", 8},
     }},
    {"get_kernel_syms",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"table", 8},
     }},  // only in kernels before Linux 2.6
    {"get_mempolicy",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"policy", 8}, [ARG_1] = {"nmask", 8},
             [ARG_2] = {"maxnode", 8}, [ARG_3] = {"addr", 8},
             [ARG_4] = {"flags", 8},
     }},
    {"getpeername",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"usockaddr", 8},
             [ARG_2] = {"usockaddr_len", 8},
     }},
    {"getpgid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4},
     }},
    {"getpgrp", TEMPLATE_NUM, NORMAL, {}},
    {"getpid", TEMPLATE_NUM, NORMAL, {}},
    {"getpmsg", TEMPLATE_NUM, NORMAL, {}},  // Unimplemented system call
    {"getppid", TEMPLATE_NUM, NORMAL, {}},
    {"getpriority",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which", 4}, [ARG_1] = {"who", 4},
     }},
    {"getrandom",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"buf", 8}, [ARG_1] = {"count", 8},
             [ARG_2] = {"flags", 4},
     }},
    {"getresgid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"rgidp", 8}, [ARG_1] = {"egidp", 8},
             [ARG_2] = {"sgidp", 8},
     }},
    {"getresuid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ruidp", 8}, [ARG_1] = {"euidp", 8},
             [ARG_2] = {"suidp", 8},
     }},
    {"getrlimit",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"resource", 4}, [ARG_1] = {"rlim", 8},
     }},
    {"get_robust_list",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"head_ptr", 8},
             [ARG_2] = {"len_ptr", 8},
     }},
    {"getrusage",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"who", 4}, [ARG_1] = {"ru", 8},
     }},
    {"getsid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4},
     }},
    {"getsockname",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"usockaddr", 8},
             [ARG_2] = {"usockaddr_len", 8},
     }},
    {"getsockopt",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"level", 4},
             [ARG_2] = {"optname", 4}, [ARG_3] = {"optval", 8},
             [ARG_4] = {"optlen", 8},
     }},
    {"get_thread_area",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"u_info", 8},
     }},
    {"gettid", TEMPLATE_NUM, NORMAL, {}},
    {"gettimeofday",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"tv", 8}, [ARG_1] = {"tz", 8},
     }},
    {"getuid", TEMPLATE_NUM, NORMAL, {}},
    {"getxattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 8}, [ARG_1] = {"name", 8},
             [ARG_2] = {"value", 8}, [ARG_3] = {"size", 8},
     }},
    {"init_module",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"umod", 8}, [ARG_1] = {"len", 8},
             [ARG_2] = {"uargs", 8},
     }},
    {"inotify_add_watch",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"pathname", 8},
             [ARG_2] = {"mask", 4},
     }},
    {"inotify_init", TEMPLATE_NUM, NORMAL, {}},
    {"inotify_init1",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"flags", 4},
     }},
    {"inotify_rm_watch",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"wd", 4},
     }},
    {"io_cancel",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ctx_id", 8}, [ARG_1] = {"iocb", 8},
             [ARG_2] = {"result", 8},
     }},
    {"ioctl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"cmd", 4}, [ARG_2] = {"arg", 8},
     }},
    {"io_destroy",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ctx", 8},
     }},
    {"io_getevents",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ctx_id", 8}, [ARG_1] = {"min_nr", 8},
             [ARG_2] = {"nr", 8}, [ARG_3] = {"events", 8},
             [ARG_4] = {"timeout", 8},
     }},
    {"ioperm",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"from", 8}, [ARG_1] = {"num", 8},
             [ARG_2] = {"turn_on", 4},
     }},
    {"iopl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"level", 4},
     }},
    {"ioprio_get",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which", 4}, [ARG_1] = {"who", 4},
     }},
    {"ioprio_set",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which", 4}, [ARG_1] = {"who", 4},
             [ARG_2] = {"ioprio", 4},
     }},
    {"io_setup",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"nr_events", 4}, [ARG_1] = {"ctxp", 8},
     }},
    {"io_submit",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ctx_id", 8}, [ARG_1] = {"nr", 8},
             [ARG_2] = {"iocbpp", 8},
     }},
    {"kcmp",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid1", 4}, [ARG_1] = {"pid2", 4},
             [ARG_2] = {"type", 4}, [ARG_3] = {"idx1", 8},
             [ARG_4] = {"idx2", 8},
     }},
    {"kexec_file_load",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"kernel_fd", 4}, [ARG_1] = {"initrd_fd", 4},
             [ARG_2] = {"cmdline_len", 8}, [ARG_3] = {"cmdline_ptr", 8},
             [ARG_4] = {"flags", 8},
     }},
    {"kexec_load",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"entry", 8}, [ARG_1] = {"nr_segments", 8},
             [ARG_2] = {"segments", 8}, [ARG_3] = {"flags", 8},
     }},
    {"keyctl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"option", 4}, [ARG_1] = {"arg2", 8},
             [ARG_2] = {"arg3", 8}, [ARG_3] = {"arg4", 8},
             [ARG_4] = {"arg5", 8},
     }},
    {"kill",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"sig", 4},
     }},
    {"lchown",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 8}, [ARG_1] = {"user", 4},
             [ARG_2] = {"group", 4},
     }},
    {"lgetxattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 8}, [ARG_1] = {"name", 8},
             [ARG_2] = {"value", 8}, [ARG_3] = {"size", 8},
     }},
    {"link",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"oldname", 8}, [ARG_1] = {"newname", 8},
     }},
    {"linkat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"olddfd", 4}, [ARG_1] = {"oldname", 8},
             [ARG_2] = {"newdfd", 4}, [ARG_3] = {"newname", 8},
             [ARG_4] = {"flags", 4},
     }},
    {"listen",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"backlog", 4},
     }},
    {"listxattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 8}, [ARG_1] = {"list", 8},
             [ARG_2] = {"size", 8},
     }},
    {"llistxattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 8}, [ARG_1] = {"list", 8},
             [ARG_2] = {"size", 8},
     }},
    {"lookup_dcookie",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"cookie64", 8}, [ARG_1] = {"buf", 8},
             [ARG_2] = {"len", 8},
     }},
    {"lremovexattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 8}, [ARG_1] = {"name", 8},
     }},
    {"lseek",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"offset", 8},
             [ARG_2] = {"whence", 4},
     }},
    {"lsetxattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 8}, [ARG_1] = {"name", 8},
             [ARG_2] = {"value", 8}, [ARG_3] = {"size", 8},
             [ARG_4] = {"flags", 4},
     }},
    {"madvise",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"start", 8}, [ARG_1] = {"len_in", 8},
             [ARG_2] = {"behavior", 4},
     }},
    {"mbind",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"start", 8}, [ARG_1] = {"len", 8},
             [ARG_2] = {"mode", 8}, [ARG_3] = {"nmask", 8},
             [ARG_4] = {"maxnode", 8}, [ARG_5] = {"flags", 4},
     }},
    {"membarrier",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"cmd", 4}, [ARG_1] = {"flags", 4},
     }},
    {"memfd_create",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"uname", 8}, [ARG_1] = {"flags", 4},
     }},
    {"migrate_pages",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"maxnode", 8},
             [ARG_2] = {"old_nodes", 8}, [ARG_3] = {"new_nodes", 8},
     }},
    {"mincore",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"start", 8}, [ARG_1] = {"len", 8}, [ARG_2] = {"vec", 8},
     }},
    {"mkdir",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 8}, [ARG_1] = {"mode", 2},
     }},
    {"mkdirat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"pathname", 8},
             [ARG_2] = {"mode", 2},
     }},
    {"mknod",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 8}, [ARG_1] = {"mode", 2},
             [ARG_2] = {"dev", 4},
     }},
    {"mknodat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"filename", 8},
             [ARG_2] = {"mode", 2}, [ARG_3] = {"dev", 4},
     }},
    {"mlock",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"start", 8}, [ARG_1] = {"len", 8},
     }},
    {"mlock2",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"start", 8}, [ARG_1] = {"len", 8},
             [ARG_2] = {"flags", 4},
     }},
    {"mlockall",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"flags", 4},
     }},
    {"mmap",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"addr", 8}, [ARG_1] = {"len", 8}, [ARG_2] = {"prot", 8},
             [ARG_3] = {"flags", 8}, [ARG_4] = {"fd", 8}, [ARG_5] = {"off", 8},
     }},
    {"modify_ldt",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"func", 4}, [ARG_1] = {"ptr", 8},
             [ARG_2] = {"bytecount", 8},
     }},
    {"mount",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dev_name", 8}, [ARG_1] = {"dir_name", 8},
             [ARG_2] = {"type", 8}, [ARG_3] = {"flags", 8},
             [ARG_4] = {"data", 8},
     }},
    {"move_pages",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"nr_pages", 8},
             [ARG_2] = {"pages", 8}, [ARG_3] = {"nodes", 8},
             [ARG_4] = {"status", 8}, [ARG_5] = {"flags", 4},
     }},
    {"mprotect",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"start", 8}, [ARG_1] = {"len", 8},
             [ARG_2] = {"prot", 8},
     }},
    {"mq_getsetattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"mqdes", 4}, [ARG_1] = {"u_mqstat", 8},
             [ARG_2] = {"u_omqstat", 8},
     }},
    {"mq_notify",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"mqdes", 4}, [ARG_1] = {"u_notification", 8},
     }},
    {"mq_open",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"u_name", 8}, [ARG_1] = {"oflag", 4},
             [ARG_2] = {"mode", 2}, [ARG_3] = {"u_attr", 8},
     }},
    {"mq_timedreceive",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"mqdes", 4}, [ARG_1] = {"u_msg_ptr", 8},
             [ARG_2] = {"msg_len", 8}, [ARG_3] = {"u_msg_prio", 8},
             [ARG_4] = {"u_abs_timeout", 8},
     }},
    {"mq_timedsend",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"mqdes", 4}, [ARG_1] = {"u_msg_ptr", 8},
             [ARG_2] = {"msg_len", 8}, [ARG_3] = {"msg_prio", 4},
             [ARG_4] = {"u_abs_timeout", 8},
     }},
    {"mq_unlink",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"u_name", 8},
     }},
    {"mremap",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"addr", 8}, [ARG_1] = {"old_len", 8},
             [ARG_2] = {"new_len", 8}, [ARG_3] = {"flags", 8},
             [ARG_4] = {"new_addr", 8},
     }},
    {"msgctl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"msqid", 4}, [ARG_1] = {"cmd", 4}, [ARG_2] = {"buf", 8},
     }},
    {"msgget",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"key", 4}, [ARG_1] = {"msgflg", 4},
     }},
    {"msgrcv",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"msqid", 4}, [ARG_1] = {"msgp", 8},
             [ARG_2] = {"msgsz", 8}, [ARG_3] = {"msgtyp", 8},
             [ARG_4] = {"msgflg", 4},
     }},
    {"msgsnd",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"msqid", 4}, [ARG_1] = {"msgp", 8},
             [ARG_2] = {"msgsz", 8}, [ARG_3] = {"msgflg", 4},
     }},
    {"msync",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"start", 8}, [ARG_1] = {"len", 8},
             [ARG_2] = {"flags", 4},
     }},
    {"munlock",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"start", 8}, [ARG_1] = {"len", 8},
     }},
    {"munlockall", TEMPLATE_NUM, NORMAL, {}},
    {"munmap",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"addr", 8}, [ARG_1] = {"len", 8},
     }},
    {"name_to_handle_at",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"name", 8},
             [ARG_2] = {"handle", 8}, [ARG_3] = {"mnt_id", 8},
             [ARG_4] = {"flag", 4},
     }},
    {"nanosleep",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"rqtp", 8}, [ARG_1] = {"rmtp", 8},
     }},
    {"fstat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"statbuf", 8},
     }},
    {"newfstat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"statbuf", 8},
     }},
    {"newfstatat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"filename", 8},
             [ARG_2] = {"statbuf", 8}, [ARG_3] = {"flag", 4},
     }},
    {"newlstat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 8}, [ARG_1] = {"statbuf", 8},
     }},
    {"lstat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 8}, [ARG_1] = {"statbuf", 8},
     }},
    {"newstat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 8}, [ARG_1] = {"statbuf", 8},
     }},
    {"stat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 8}, [ARG_1] = {"statbuf", 8},
     }},
    {"newuname",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"name", 8},
     }},
    {"uname",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"name", 8},
     }},
    {"nfsservctl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"cmd", 4}, [ARG_1] = {"argp", 8}, [ARG_2] = {"resp", 8},
     }},  // only in kernels before Linux 3.1
    {"open",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 8}, [ARG_1] = {"flags", 4},
             [ARG_2] = {"mode", 2},
     }},
    {"openat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"filename", 8},
             [ARG_2] = {"flags", 4}, [ARG_3] = {"mode", 2},
     }},
    {"open_by_handle_at",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"mountdirfd", 4}, [ARG_1] = {"handle", 8},
             [ARG_2] = {"flags", 4},
     }},
    {"pause", TEMPLATE_NUM, NORMAL, {}},
    {"perf_event_open",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"attr_uptr", 8}, [ARG_1] = {"pid", 4},
             [ARG_2] = {"cpu", 4}, [ARG_3] = {"group_fd", 4},
             [ARG_4] = {"flags", 8},
     }},
    {"personality",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"personality", 4},
     }},
    {"pipe",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fildes", 8},
     }},
    {"pipe2",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fildes", 8}, [ARG_1] = {"flags", 4},
     }},
    {"pivot_root",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"new_root", 8}, [ARG_1] = {"put_old", 8},
     }},
    {"poll",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ufds", 8}, [ARG_1] = {"nfds", 4},
             [ARG_2] = {"timeout_msecs", 4},
     }},
    {"ppoll",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ufds", 8}, [ARG_1] = {"nfds", 4}, [ARG_2] = {"tsp", 8},
             [ARG_3] = {"sigmask", 8}, [ARG_4] = {"sigsetsize", 8},
     }},
    {"prctl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"option", 4}, [ARG_1] = {"arg2", 8},
             [ARG_2] = {"arg3", 8}, [ARG_3] = {"arg4", 8},
             [ARG_4] = {"arg5", 8},
     }},
    {"pread64",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"buf", 8}, [ARG_2] = {"count", 8},
             [ARG_3] = {"pos", 8},
     }},
    {"preadv",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 8}, [ARG_1] = {"vec", 8}, [ARG_2] = {"vlen", 8},
             [ARG_3] = {"pos_l", 8}, [ARG_4] = {"pos_h", 8},
     }},
    {"preadv2",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 8}, [ARG_1] = {"vec", 8}, [ARG_2] = {"vlen", 8},
             [ARG_3] = {"pos_l", 8}, [ARG_4] = {"pos_h", 8},
             [ARG_5] = {"flags", 4},
     }},
    {"prlimit64",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"resource", 4},
             [ARG_2] = {"new_rlim", 8}, [ARG_3] = {"old_rlim", 8},
     }},
    {"process_vm_readv",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"lvec", 8},
             [ARG_2] = {"liovcnt", 8}, [ARG_3] = {"rvec", 8},
             [ARG_4] = {"riovcnt", 8}, [ARG_5] = {"flags", 8},
     }},
    {"process_vm_writev",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"lvec", 8},
             [ARG_2] = {"liovcnt", 8}, [ARG_3] = {"rvec", 8},
             [ARG_4] = {"riovcnt", 8}, [ARG_5] = {"flags", 8},
     }},
    {"pselect6",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"n", 4}, [ARG_1] = {"inp", 8}, [ARG_2] = {"outp", 8},
             [ARG_3] = {"exp", 8}, [ARG_4] = {"tsp", 8}, [ARG_5] = {"sig", 8},
     }},
    {"ptrace",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"request", 8}, [ARG_1] = {"pid", 8},
             [ARG_2] = {"addr", 8}, [ARG_3] = {"data", 8},
     }},
    {"putpmsg", TEMPLATE_NUM, NORMAL, {}},  // Unimplemented system call
    {"pwrite64",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"buf", 8}, [ARG_2] = {"count", 8},
             [ARG_3] = {"pos", 8},
     }},
    {"pwritev",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 8}, [ARG_1] = {"vec", 8}, [ARG_2] = {"vlen", 8},
             [ARG_3] = {"pos_l", 8}, [ARG_4] = {"pos_h", 8},
     }},
    {"pwritev2",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 8}, [ARG_1] = {"vec", 8}, [ARG_2] = {"vlen", 8},
             [ARG_3] = {"pos_l", 8}, [ARG_4] = {"pos_h", 8},
             [ARG_5] = {"flags", 4},
     }},
    {"query_module",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"name", 8}, [ARG_1] = {"which", 4},
             [ARG_2] = {"buf", 8}, [ARG_3] = {"bufsize", 8},
             [ARG_4] = {"ret", 8},
     }},  // only in kernels before Linux 2.6
    {"quotactl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"cmd", 4}, [ARG_1] = {"special", 8},
             [ARG_2] = {"id", 4}, [ARG_3] = {"addr", 8},
     }},
    {"read",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"buf", 8}, [ARG_2] = {"count", 8},
     }},
    {"readahead",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"offset", 8},
             [ARG_2] = {"count", 8},
     }},
    {"readlink",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"path", 8}, [ARG_1] = {"buf", 8},
             [ARG_2] = {"bufsiz", 4},
     }},
    {"readlinkat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"pathname", 8},
             [ARG_2] = {"buf", 8}, [ARG_3] = {"bufsiz", 4},
     }},
    {"readv",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 8}, [ARG_1] = {"vec", 8}, [ARG_2] = {"vlen", 8},
     }},
    {"reboot",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"magic1", 4}, [ARG_1] = {"magic2", 4},
             [ARG_2] = {"cmd", 4}, [ARG_3] = {"arg", 8},
     }},
    {"recvfrom",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"ubuf", 8}, [ARG_2] = {"size", 8},
             [ARG_3] = {"flags", 4}, [ARG_4] = {"addr", 8},
             [ARG_5] = {"addr_len", 8},
     }},
    {"recvmmsg",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"mmsg", 8}, [ARG_2] = {"vlen", 4},
             [ARG_3] = {"flags", 4}, [ARG_4] = {"timeout", 8},
     }},
    {"recvmsg",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"msg", 8}, [ARG_2] = {"flags", 4},
     }},
    {"remap_file_pages",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"start", 8}, [ARG_1] = {"size", 8},
             [ARG_2] = {"prot", 8}, [ARG_3] = {"pgoff", 8},
             [ARG_4] = {"flags", 8},
     }},
    {"removexattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 8}, [ARG_1] = {"name", 8},
     }},
    {"rename",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"oldname", 8}, [ARG_1] = {"newname", 8},
     }},
    {"renameat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"olddfd", 4}, [ARG_1] = {"oldname", 8},
             [ARG_2] = {"newdfd", 4}, [ARG_3] = {"newname", 8},
     }},
    {"renameat2",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"olddfd", 4}, [ARG_1] = {"oldname", 8},
             [ARG_2] = {"newdfd", 4}, [ARG_3] = {"newname", 8},
             [ARG_4] = {"flags", 4},
     }},
    {"request_key",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"_type", 8}, [ARG_1] = {"_description", 8},
             [ARG_2] = {"_callout_info", 8}, [ARG_3] = {"destringid", 4},
     }},
    {"restart_syscall", TEMPLATE_NUM, NORMAL, {}},
    {"rmdir",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 8},
     }},
    {"rt_sigaction",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"sig", 4}, [ARG_1] = {"act", 8}, [ARG_2] = {"oact", 8},
             [ARG_3] = {"sigsetsize", 8},
     }},
    {"rt_sigpending",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"uset", 8}, [ARG_1] = {"sigsetsize", 8},
     }},
    {"rt_sigprocmask",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"how", 4}, [ARG_1] = {"nset", 8}, [ARG_2] = {"oset", 8},
             [ARG_3] = {"sigsetsize", 8},
     }},
    {"rt_sigqueueinfo",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"sig", 4}, [ARG_2] = {"uinfo", 8},
     }},
    {"rt_sigreturn", TEMPLATE_NUM, NORMAL, {}},
    {"rt_sigsuspend",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"unewset", 8}, [ARG_1] = {"sigsetsize", 8},
     }},
    {"rt_sigtimedwait",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"uthese", 8}, [ARG_1] = {"uinfo", 8},
             [ARG_2] = {"uts", 8}, [ARG_3] = {"sigsetsize", 8},
     }},
    {"rt_tgsigqueueinfo",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"tgid", 4}, [ARG_1] = {"pid", 4}, [ARG_2] = {"sig", 4},
             [ARG_3] = {"uinfo", 8},
     }},
    {"sched_getaffinity",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"len", 4},
             [ARG_2] = {"user_mask_ptr", 8},
     }},
    {"sched_getattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"uattr", 8},
             [ARG_2] = {"size", 4}, [ARG_3] = {"flags", 4},
     }},
    {"sched_getparam",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"param", 8},
     }},
    {"sched_get_priority_max",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"policy", 4},
     }},
    {"sched_get_priority_min",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"policy", 4},
     }},
    {"sched_getscheduler",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4},
     }},
    {"sched_rr_get_interval",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"interval", 8},
     }},
    {"sched_setaffinity",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"len", 4},
             [ARG_2] = {"user_mask_ptr", 8},
     }},
    {"sched_setattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"uattr", 8},
             [ARG_2] = {"flags", 4},
     }},
    {"sched_setparam",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"param", 8},
     }},
    {"sched_setscheduler",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"policy", 4},
             [ARG_2] = {"param", 8},
     }},
    {"sched_yield", TEMPLATE_NUM, NORMAL, {}},
    {"seccomp",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"op", 4}, [ARG_1] = {"flags", 4},
             [ARG_2] = {"uargs", 8},
     }},
    {"security", TEMPLATE_NUM, NORMAL, {}},  // Unimplemented system call
    {"select",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"n", 4}, [ARG_1] = {"inp", 8}, [ARG_2] = {"outp", 8},
             [ARG_3] = {"exp", 8}, [ARG_4] = {"tvp", 8},
     }},
    {"newselect",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"n", 4}, [ARG_1] = {"inp", 8}, [ARG_2] = {"outp", 8},
             [ARG_3] = {"exp", 8}, [ARG_4] = {"tvp", 8},
     }},
    {"_newselect",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"n", 4}, [ARG_1] = {"inp", 8}, [ARG_2] = {"outp", 8},
             [ARG_3] = {"exp", 8}, [ARG_4] = {"tvp", 8},
     }},
    {"semctl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"semid", 4}, [ARG_1] = {"semnum", 4},
             [ARG_2] = {"cmd", 4}, [ARG_3] = {"arg", 8},
     }},
    {"semget",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"key", 4}, [ARG_1] = {"nsems", 4},
             [ARG_2] = {"semflg", 4},
     }},
    {"semop",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"semid", 4}, [ARG_1] = {"tsops", 8},
             [ARG_2] = {"nsops", 4},
     }},
    {"semtimedop",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"semid", 4}, [ARG_1] = {"tsops", 8},
             [ARG_2] = {"nsops", 4}, [ARG_3] = {"timeout", 8},
     }},
    {"sendfile",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"out_fd", 4}, [ARG_1] = {"in_fd", 4},
             [ARG_2] = {"offset", 4}, [ARG_3] = {"count", 4},
     }},
    {"sendfile64",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"out_fd", 4}, [ARG_1] = {"in_fd", 4},
             [ARG_2] = {"offset", 8}, [ARG_3] = {"count", 8},
     }},
    {"sendmmsg",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"mmsg", 8}, [ARG_2] = {"vlen", 4},
             [ARG_3] = {"flags", 4},
     }},
    {"sendmsg",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"msg", 8}, [ARG_2] = {"flags", 4},
     }},
    {"sendto",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"buff", 8}, [ARG_2] = {"len", 8},
             [ARG_3] = {"flags", 4}, [ARG_4] = {"addr", 8},
             [ARG_5] = {"addr_len", 4},
     }},
    {"setdomainname",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"name", 8}, [ARG_1] = {"len", 4},
     }},
    {"setfsgid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"gid", 4},
     }},
    {"setfsuid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"uid", 4},
     }},
    {"setgid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"gid", 4},
     }},
    {"setgroups",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"gidsetsize", 4}, [ARG_1] = {"grouplist", 8},
     }},
    {"sethostname",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"name", 8}, [ARG_1] = {"len", 4},
     }},
    {"setitimer",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which", 4}, [ARG_1] = {"value", 8},
             [ARG_2] = {"ovalue", 8},
     }},
    {"set_mempolicy",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"mode", 4}, [ARG_1] = {"nmask", 8},
             [ARG_2] = {"maxnode", 8},
     }},
    {"setns",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"nstype", 4},
     }},
    {"setpgid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"pgid", 4},
     }},
    {"setpriority",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which", 4}, [ARG_1] = {"who", 4},
             [ARG_2] = {"niceval", 4},
     }},
    {"setregid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"rgid", 4}, [ARG_1] = {"egid", 4},
     }},
    {"setresgid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"rgid", 4}, [ARG_1] = {"egid", 4},
             [ARG_2] = {"sgid", 4},
     }},
    {"setresuid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ruid", 4}, [ARG_1] = {"euid", 4},
             [ARG_2] = {"suid", 4},
     }},
    {"setreuid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ruid", 4}, [ARG_1] = {"euid", 4},
     }},
    {"setrlimit",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"resource", 4}, [ARG_1] = {"rlim", 8},
     }},
    {"set_robust_list",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"head", 8}, [ARG_1] = {"len", 8},
     }},
    {"setsid", TEMPLATE_NUM, NORMAL, {}},
    {"setsockopt",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"level", 4},
             [ARG_2] = {"optname", 4}, [ARG_3] = {"optval", 8},
             [ARG_4] = {"optlen", 4},
     }},
    {"set_thread_area",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"u_info", 8},
     }},
    {"set_tid_address",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"tidptr", 8},
     }},
    {"settimeofday",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"tv", 8}, [ARG_1] = {"tz", 8},
     }},
    {"setuid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"uid", 4},
     }},
    {"setxattr",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 8}, [ARG_1] = {"name", 8},
             [ARG_2] = {"value", 8}, [ARG_3] = {"size", 8},
             [ARG_4] = {"flags", 4},
     }},
    {"shmat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"shmid", 4}, [ARG_1] = {"shmaddr", 8},
             [ARG_2] = {"shmflg", 4},
     }},
    {"shmctl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"shmid", 4}, [ARG_1] = {"cmd", 4}, [ARG_2] = {"buf", 8},
     }},
    {"shmdt",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"shmaddr", 8},
     }},
    {"shmget",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"key", 4}, [ARG_1] = {"size", 8},
             [ARG_2] = {"shmflg", 4},
     }},
    {"shutdown",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"how", 4},
     }},
    {"sigaltstack",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"uss", 8}, [ARG_1] = {"uoss", 8},
     }},
    {"signalfd",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ufd", 4}, [ARG_1] = {"user_mask", 8},
             [ARG_2] = {"sizemask", 8},
     }},
    {"signalfd4",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ufd", 4}, [ARG_1] = {"user_mask", 8},
             [ARG_2] = {"sizemask", 8}, [ARG_3] = {"flags", 4},
     }},
    {"socket",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"family", 4}, [ARG_1] = {"type", 4},
             [ARG_2] = {"protocol", 4},
     }},
    {"socketpair",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"family", 4}, [ARG_1] = {"type", 4},
             [ARG_2] = {"protocol", 4}, [ARG_3] = {"usockvec", 8},
     }},
    {"splice",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd_in", 4}, [ARG_1] = {"off_in", 8},
             [ARG_2] = {"fd_out", 4}, [ARG_3] = {"off_out", 8},
             [ARG_4] = {"len", 8}, [ARG_5] = {"flags", 4},
     }},
    {"statfs",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 8}, [ARG_1] = {"buf", 8},
     }},
    {"swapoff",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"specialfile", 8},
     }},
    {"swapon",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"specialfile", 8}, [ARG_1] = {"swap_flags", 4},
     }},
    {"symlink",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"oldname", 8}, [ARG_1] = {"newname", 8},
     }},
    {"symlinkat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"oldname", 8}, [ARG_1] = {"newdfd", 4},
             [ARG_2] = {"newname", 8},
     }},
    {"sync", TEMPLATE_NUM, NORMAL, {}},
    {"sync_file_range",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"offset", 8},
             [ARG_2] = {"nbytes", 8}, [ARG_3] = {"flags", 4},
     }},
    {"syncfs",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4},
     }},
    {"sysctl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"args", 8},
     }},
    {"_sysctl",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"args", 8},
     }},
    {"sysfs",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"option", 4}, [ARG_1] = {"arg1", 8},
             [ARG_2] = {"arg2", 8},
     }},
    {"sysinfo",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"info", 8},
     }},
    {"syslog",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"type", 4}, [ARG_1] = {"buf", 8}, [ARG_2] = {"len", 4},
     }},
    {"tee",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fdin", 4}, [ARG_1] = {"fdout", 4},
             [ARG_2] = {"len", 8}, [ARG_3] = {"flags", 4},
     }},
    {"tgkill",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"tgid", 4}, [ARG_1] = {"pid", 4}, [ARG_2] = {"sig", 4},
     }},
    {"time",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"tloc", 8},
     }},
    {"timer_create",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which_clock", 4}, [ARG_1] = {"timer_event_spec", 8},
             [ARG_2] = {"created_timer_id", 8},
     }},
    {"timer_delete",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"timer_id", 4},
     }},
    {"timerfd_create",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"clockid", 4}, [ARG_1] = {"flags", 4},
     }},
    {"timerfd_gettime",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ufd", 4}, [ARG_1] = {"otmr", 8},
     }},
    {"timerfd_settime",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"ufd", 4}, [ARG_1] = {"flags", 4},
             [ARG_2] = {"utmr", 8}, [ARG_3] = {"otmr", 8},
     }},
    {"timer_getoverrun",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"timer_id", 4},
     }},
    {"timer_gettime",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"timer_id", 4}, [ARG_1] = {"setting", 8},
     }},
    {"timer_settime",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"timer_id", 4}, [ARG_1] = {"flags", 4},
             [ARG_2] = {"new_setting", 8}, [ARG_3] = {"old_setting", 8},
     }},
    {"times",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"tbuf", 8},
     }},
    {"tkill",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pid", 4}, [ARG_1] = {"sig", 4},
     }},
    {"truncate",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"path", 8}, [ARG_1] = {"length", 8},
     }},
    {"tuxcall", TEMPLATE_NUM, NORMAL, {}},  // Unimplemented system call
    {"umask",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"mask", 4},
     }},
    {"umount",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"name", 8}, [ARG_1] = {"flags", 4},
     }},
    {"umount2",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"name", 8}, [ARG_1] = {"flags", 4},
     }},
    {"unlink",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"pathname", 8},
     }},
    {"unlinkat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"pathname", 8},
             [ARG_2] = {"flag", 4},
     }},
    {"unshare",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"unshare_flags", 8},
     }},
    {"uselib",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"library", 8},
     }},
    {"userfaultfd",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"flags", 4},
     }},
    {"ustat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dev", 4}, [ARG_1] = {"ubuf", 8},
     }},
    {"utime",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 8}, [ARG_1] = {"times", 8},
     }},
    {"utimensat",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"dfd", 4}, [ARG_1] = {"filename", 8},
             [ARG_2] = {"utimes", 8}, [ARG_3] = {"flags", 4},
     }},
    {"utimes",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"filename", 8}, [ARG_1] = {"utimes", 8},
     }},
    {"vfork", TEMPLATE_NUM, NORMAL, {}},
    {"vhangup", TEMPLATE_NUM, NORMAL, {}},
    {"vmsplice",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"iov", 8},
             [ARG_2] = {"nr_segs", 8}, [ARG_3] = {"flags", 4},
     }},
    {"vserver", TEMPLATE_NUM, NORMAL, {}},  // Unimplemented system call
    {"write",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 4}, [ARG_1] = {"buf", 4}, [ARG_2] = {"count", 4},
     }},
    {"wait4",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"upid", 4}, [ARG_1] = {"stat_addr", 8},
             [ARG_2] = {"options", 4}, [ARG_3] = {"ru", 8},
     }},
    {"waitid",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"which", 4}, [ARG_1] = {"upid", 4},
             [ARG_2] = {"infop", 8}, [ARG_3] = {"options", 4},
             [ARG_4] = {"ru", 8},
     }},
    {"writev",
     TEMPLATE_NUM,
     NORMAL,
     {
             [ARG_0] = {"fd", 8}, [ARG_1] = {"vec", 8}, [ARG_2] = {"vlen", 8},
     }},
};

const size_t TEMPALTE_ARCH_syscall_list_size =
    sizeof(TEMPALTE_ARCH_syscall_list) / sizeof(TEMPALTE_ARCH_syscall_list[0]);
